### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by NN---** [JasonWei512/Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode#1]

**Comment by JasonWei512** [comment]
[Auto Theme Switcher 2022 Beta bdbc38a.zip](https://github.com/JasonWei512/Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode/files/6774154/Auto.Theme.Switcher.2022.Beta.bdbc38a.zip)
I am experimenting Visual Studio 2022 support on the develop branch. Here's an experimental build. 
I've tested it on Visual Studio 2019 & 2022 Community. It should work on 2017 too.
Any contribution or feedback is welcome.

**Comment by NN---** [comment]
There is Releases page in GitHub where you should put it: https://github.com/JasonWei512/releases .
You have to enable it for this repository.

**Comment by JasonWei512** [comment]
I have submitted v0.8 to [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=NickJohn.AutoThemeSwitcherForWin10DarkMode) with Visual Studio 2022 support.

**Comment by JasonWei512** [comment]
VS 2022 now has a built-in "use system theme" option. But the default light theme for light system theme is "Blue", not "Light", and you can't change it.
![image](https://user-images.githubusercontent.com/16899918/129165220-66564d2b-c3f8-443b-9402-6f088828a118.png)
