### ISSUE TITLE
請問這個在vs 2022中有用嗎

### ISSUE THREAD

**Issue by seanmamasde** [JasonWei512/Visual-Studio-Auto-Theme-Switcher-for-Win10-Dark-Mode#3]
如題

**Comment by JasonWei512** [comment]
可以，我自己就在用。
不过它不支持 ARM64，所以可能在 Windows on ARM 设备上用不了。

**Comment by seanmamasde** [comment]
@JasonWei512 了解。那可以再請問你是怎麼設定讓windows 11在light mode的時候切換成vs2022的light theme(內建的那個)，然後在windows 11是dark mode的時候切換成vs2022內建的dark theme? 我從tools > themes底下只有看到use system settings那個選項，但是選了之後在light mode時會切換成blue(內建的那個)；我還試過從tools > options > auto theme switcher(這個擴充的設定那邊直接調成上述的light->light, dark->dark)，但是他還是維持light->blue，謝謝。

**Comment by JasonWei512** [comment]
你打开 Tools > Options，在 Environment 里把 Visual Studio 的主题设置成 “Use system settings” 以外的选项（比如 “Dark”），再在 Auto Theme Switcher 的设定里设定 Light -> Light / Dark -> Dark，然后再确认试试。

**Comment by seanmamasde** [comment]
感謝，有用了
